### PR TITLE
Fixbrand

### PR DESCRIPTION
**Pull request by Gautier**

### CODE REVIEW

**Comment by Keats** [comment]
no other reference of mitro in templates?

**Comment by Gautier** [comment]
As far as I can see, no. But then the whole game is to find these references

**Comment by Keats** [comment]
https://github.com/WeAreWizards/passopolis-server/search?l=html%2Bdjango&q=mitro&utf8=%E2%9C%93 seems like a couple more

**Comment by Gautier** [comment]
I think the search is not limited to this branch. There were still a few mentions in the TFA errors. The CSS is quite different from our current page so I'm just going to leave them as-is until we redo our design.

**Comment by Gautier** [comment]
FYI the tests pass

**Comment by teh** [comment]
LGTM, neat!

**Pull request merged**
