### PR TITLE
Device verification email contains request IP

### PR DESCRIPTION
**Pull request by Gautier**

### CODE REVIEW

**Comment by Gautier** [comment]
This is covering issue #7 and also needs https://github.com/WeAreWizards/passopolis-mail-queue/pull/1

**Comment by teh** [comment]
Assuming you tested this LGTM - nice about being careful about the update path (field there, not there).

**Comment by Gautier** [comment]
I have manually tested the Haskell part and the Java part is covered by unit test (and manually debugging output during development) but I haven't tested them together in a production-like environment.

When it goes live it would need to be immediately tested by registering a new user and device and checking the notification.

I can own the deployment + testing if you're cool with that (and if I manage to get the nixops gods with me).

**Comment by Gautier** [comment]
The previous comment isn't all correct actually. The Java code merely gets exercised by the tests, there are no asserts regarding the extra field. It was only tested using debugging output during development.

**Pull request merged**
